### ISSUE TITLE
RtMidiError build errors

### ISSUE THREAD

**Issue by trideceth12** [allan-simon/linthesia#83]
Building cbc0d26c07

Build output:

    g++ -DHAVE_CONFIG_H -I. -I..  -DGRAPHDIR="\"../graphics\"" -D__UNIX_JACK__ -D__LINUX_ALSA__    -Wall -std=c++11 -iquote ../libmidi -g -O2 -std=c++11 -MT midi_io/linthesia-midi_in.o -MD -MP -MF midi_io/.deps/linthesia-midi_in.Tpo -c -o midi_io/linthesia-midi_in.o `test -f 'midi_io/midi_in.cpp' || echo './'`midi_io/midi_in.cpp
    midi_io/midi_in.cpp: In member function ‘void linthesia::MidiIn::open()’:
    midi_io/midi_in.cpp:62:12: error: expected type-specifier before ‘RtMidiError’
         catch (RtMidiError &error) {
                ^
    midi_io/midi_in.cpp:62:24: error: expected ‘)’ before ‘&’ token
         catch (RtMidiError &error) {
                            ^
    midi_io/midi_in.cpp:62:24: error: expected ‘{’ before ‘&’ token
    midi_io/midi_in.cpp:62:25: error: ‘error’ was not declared in this scope
         catch (RtMidiError &error) {
                             ^
    midi_io/midi_in.cpp:62:30: error: expected ‘;’ before ‘)’ token
         catch (RtMidiError &error) {
                                  ^
    make[2]: *** [midi_io/linthesia-midi_in.o] Error 1
    make[2]: Leaving directory `/home/manko/Repos/allan-simon/linthesia/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/manko/Repos/allan-simon/linthesia'
    make: *** [all] Error 2

Version:

    $ g++ --version
    g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by allan-simon** [comment]
Hello thanks for the bug report, can you tell me on which version of ubuntu you are ?

**Comment by trideceth12** [comment]
Give me a sec, I fixed it myself - I'll send you a pull request (with a couple of other things too)

**Comment by trideceth12** [comment]
Ahh.. Actually RtMidi 2.1 changed the API from RtError to RtMidiError, so it's just that I was using an older version of the lib.
