### ISSUE TITLE
 Switch away from timidity

### ISSUE THREAD

**Issue by Elinvention** [allan-simon/linthesia#86]
Timidity is not maintained anymore and this project should not depend on an external daemon synthesizer as it makes it harder to use. To make things worse, timidity has no support for PulseAudio which is almost a standard on every modern distribution (e.g. GNOME requires it).

I think we should find a library to embed a midi synthesizer into linthesia that supports PulseAudio and all the others you want.

**Comment by allan-simon** [comment]
thanks for the feedback,  I don't have so much time recently, but if you were to advice me such a library, i would happily work on integrating it :)

**Comment by allan-simon** [comment]
I've seen http://fluidsynth.sourceforge.net/api/index.html , but I was wondering if it shoulnd't be instead a new backend for rtmidi instead https://github.com/thestk/rtmidi (the library i rely on for midi input/output currently)

**Comment by Elinvention** [comment]
Oh I thought Linthesia used timidity directly sorry. Instead it uses a rtmidi to route "traffic" between midi devices... Indeed I was able to start FluidSynth with a GUI called QSynth and tell linthesia to use it. Finally sound through PulseAudio!

If rtmidi had a backend for FluiSynth then we wouldn't have to start another program before linthesia. This would be a nice solution.

**Comment by Elinvention** [comment]
In the end this is not an issue of linthesia.

**Comment by allan-simon** [comment]
I added a note on the readme about fluisynth

**Comment by baptx** [comment]
@Elinvention @allan-simon we can use TiMidity++ which is maintained (https://github.com/linthesia/linthesia/issues/41#issuecomment-850911873). Is there an advantage to use FluidSynth instead of TiMidity++ with Linthesia?

**Comment by allan-simon** [comment]
@baptx  you're right for run vs install

 As we have a pretty simple usage of midi,  Timidity++ will also work,  feel free to provide me with a patch,  I'm not developing actively this project , but as you can see i'm pretty reactive :)  so I can review PR pretty quickly
